!all mapping is on Mode_switch
keycode 66 = Mode_switch

! vim like movement
!keysym h = h H Left Left
!keysym j = j J Down Down
!keysym k = k K Up  Up
!keysym l = l L Right Right
!keysym u = u U Prior
!keysym i = i I Home
!keysym o = o O End
!keysym p = p P Next

! minila like BackSpace
!keysym semicolon = semicolon colon BackSpace BackSpace

! Extend2 of DreymaR’s Extend Layer like navigation
keysym a = a A Left Left
keysym s = s S Down Down
keysym w = w W Up  Up
keysym d = d D Right Right
keysym q = q Q Home Home
keysym e = e E End End
keysym r = r R Delete Delete
keysym f = f F BackSpace BackSpace

!space also as backspace
keysym space = space space BackSpace BackSpace

!leftshift rightmost symbol
!keysym u = u U parenleft parenleft
!keysym i = i I parenright parenright
!keysym o = o O minus minus
!keysym p = p P plus plus
!
!keysym j = j J braceleft braceleft
!keysym k = k K braceright braceright
!keysym l = l L underscore underscore
!keysym semicolon = semicolon colon equal equal
!
!keysym m = m M bracketleft bracketleft
!keysym comma = comma less bracketright bracketright
!keysym period = period greater bar bar
!keysym slash = slash question backslash backslash
